[Simulation]

    # seed = 1234
    tickunit = 'd'
    GlobalSetting = false
    startdate = '2024-01-01'
    enddate = '2024-12-31'
    [Simulation.StartCondition]
        type = "InfectedFraction"
        [Simulation.StartCondition.parameters]
            fraction = 0.001
            #pathogen = "Covid19"

    [Simulation.StopCriterion]
        type = "TimesUp"
        [Simulation.StopCriterion.parameters]
            limit = 365

[Population]
    n = 100_000
    avg_household_size = 3
    avg_office_size = 5
    avg_school_size = 100
    empty = false

[Pathogens]

    [Pathogens.Covid19]
        [Pathogens.Covid19.transmission_function]
            type = "SettingRate"
            [Pathogens.Covid19.transmission_function.parameters]
                general_rate = 0.1
                household_rate = 0.3

        [Pathogens.Covid19.progressions]

            # ASYMPTOMATIC PROGRESSION [TOTAL DURATION ~ 10 DAYS]
            [Pathogens.Covid19.progressions.Asymptomatic]
                # time to infectiousness (after exposure) [+1 will be added internally to avoid zero-day durations]
                [Pathogens.Covid19.progressions.Asymptomatic.exposure_to_infectiousness_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to recovery (after infectiousness onset)
                [Pathogens.Covid19.progressions.Asymptomatic.infectiousness_onset_to_recovery]
                    distribution = "Poisson"
                    parameters = [8]

            # SYMPTOMATIC PROGRESSION [TOTAL DURATION ~ 10 DAYS]
            [Pathogens.Covid19.progressions.Symptomatic]
                # time to infectiousness (after exposure) [+1 will be added internally to avoid zero-day durations]
                [Pathogens.Covid19.progressions.Symptomatic.exposure_to_infectiousness_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to symptom onset (after infectiousness onset)
                [Pathogens.Covid19.progressions.Symptomatic.infectiousness_onset_to_symptom_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to recovery (after symptom onset)
                [Pathogens.Covid19.progressions.Symptomatic.symptom_onset_to_recovery]
                    distribution = "Poisson"
                    parameters = [7]

            # SEVERE PROGRESSION [TOTAL DURATION ~ 15 DAYS]
            [Pathogens.Covid19.progressions.Severe]
                # time to infectiousness (after exposure) [+1 will be added internally to avoid zero-day durations]
                [Pathogens.Covid19.progressions.Severe.exposure_to_infectiousness_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to symptom onset (after infectiousness onset)
                [Pathogens.Covid19.progressions.Severe.infectiousness_onset_to_symptom_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to severeness onset (after symptom onset)
                [Pathogens.Covid19.progressions.Severe.symptom_onset_to_severeness_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to severeness offset (after severeness onset)
                [Pathogens.Covid19.progressions.Severe.severeness_onset_to_severeness_offset]
                    distribution = "Poisson"
                    parameters = [7]
                # time to recovery (after severeness offset)
                [Pathogens.Covid19.progressions.Severe.severeness_offset_to_recovery]
                    distribution = "Poisson"
                    parameters = [4]

            # HOSPITALIZED PROGRESSION [TOTAL DURATION ~ 20 DAYS]
            [Pathogens.Covid19.progressions.Hospitalized]
                # time to infectiousness (after exposure) [+1 will be added internally to avoid zero-day durations]
                [Pathogens.Covid19.progressions.Hospitalized.exposure_to_infectiousness_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to symptom onset (after infectiousness onset)
                [Pathogens.Covid19.progressions.Hospitalized.infectiousness_onset_to_symptom_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to severeness onset (after symptom onset)
                [Pathogens.Covid19.progressions.Hospitalized.symptom_onset_to_severeness_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to hospitalization (after severeness onset)
                [Pathogens.Covid19.progressions.Hospitalized.severeness_onset_to_hospital_admission]
                    distribution = "Poisson"
                    parameters = [2]
                # time to recovery (after hospitalization)
                [Pathogens.Covid19.progressions.Hospitalized.hospital_admission_to_hospital_discharge]
                    distribution = "Poisson"
                    parameters = [7]
                # time to recovery (after hospital discharge)
                [Pathogens.Covid19.progressions.Hospitalized.hospital_discharge_to_severeness_offset]
                    distribution = "Poisson"
                    parameters = [3]
                [Pathogens.Covid19.progressions.Hospitalized.severeness_offset_to_recovery]
                    distribution = "Poisson"
                    parameters = [4]

            # CRITICAL PROGRESSION [TOTAL DURATION ~ 30 DAYS]
            [Pathogens.Covid19.progressions.Critical]
                # probability of death (after ICU admission)
                death_probability = 0.3
                
                # time to infectiousness (after exposure) [+1 will be added internally to avoid zero-day durations]
                [Pathogens.Covid19.progressions.Critical.exposure_to_infectiousness_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to symptom onset (after infectiousness onset)
                [Pathogens.Covid19.progressions.Critical.infectiousness_onset_to_symptom_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to severeness onset (after symptom onset)
                [Pathogens.Covid19.progressions.Critical.symptom_onset_to_severeness_onset]
                    distribution = "Poisson"
                    parameters = [1]
                # time to hospitalization (after severeness onset)
                [Pathogens.Covid19.progressions.Critical.severeness_onset_to_hospital_admission]
                    distribution = "Poisson"
                    parameters = [2]
                # time to ICU admission (after hospitalization)
                [Pathogens.Covid19.progressions.Critical.hospital_admission_to_icu_admission]
                    distribution = "Poisson"
                    parameters = [2]
                
                # RECOVERY PATHWAY
                # time to ICU discharge (after ICU admission)
                [Pathogens.Covid19.progressions.Critical.icu_admission_to_icu_discharge]
                    distribution = "Poisson"
                    parameters = [7]
                # time to hospital discharge (after ICU discharge)
                [Pathogens.Covid19.progressions.Critical.icu_discharge_to_hospital_discharge]
                    distribution = "Poisson"
                    parameters = [7]
                # time to recovery (after hospital discharge)
                [Pathogens.Covid19.progressions.Critical.hospital_discharge_to_severeness_offset]
                    distribution = "Poisson"
                    parameters = [3]
                [Pathogens.Covid19.progressions.Critical.severeness_offset_to_recovery]
                    distribution = "Poisson"
                    parameters = [4]

                # DEATH PATHWAY
                # time to death (after ICU admission)
                [Pathogens.Covid19.progressions.Critical.icu_admission_to_death]
                    distribution = "Poisson"
                    parameters = [10]

        # progression assignment method
        [Pathogens.Covid19.progression_assignment]
            type = "AgeBasedProgressionAssignment"
            [Pathogens.Covid19.progression_assignment.parameters]
                #progression_categories = ["Asymptomatic", "Symptomatic", "Hospitalized", "Critical"]
                # Matrix with Disease Progression
                age_groups = ["-14", "15-65", "66-"]
                progression_categories = ["Asymptomatic", "Symptomatic", "Severe", "Hospitalized", "Critical"]
                stratification_matrix = [[0.400, 0.580, 0.010, 0.007, 0.003], # age group -14
                                         [0.250, 0.600, 0.110, 0.030, 0.010], # age group 15-65
                                         [0.150, 0.400, 0.250, 0.120, 0.080]] # age group 66-

[Settings]

    [Settings.Household]
        [Settings.Household.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Household.contact_sampling_method.parameters]
                    contactparameter = 1.0

    [Settings.Office]
        [Settings.Office.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Office.contact_sampling_method.parameters]
                    contactparameter = 1.0
                    
    [Settings.School]
        [Settings.School.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.School.contact_sampling_method.parameters]
                    contactparameter = 1.0

    [Settings.SchoolClass]
        [Settings.SchoolClass.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.SchoolClass.contact_sampling_method.parameters]
                    contactparameter = 1.0

    [Settings.Municipality]
        [Settings.Municipality.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Municipality.contact_sampling_method.parameters]
                    contactparameter = 1.0

    [Settings.WorkplaceSite]
        [Settings.WorkplaceSite.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.WorkplaceSite.contact_sampling_method.parameters]
                    contactparameter = 1.0

    [Settings.SchoolComplex]
        [Settings.SchoolComplex.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.SchoolComplex.contact_sampling_method.parameters]
                    contactparameter = 1.0

    [Settings.SchoolYear]
        [Settings.SchoolYear.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.SchoolYear.contact_sampling_method.parameters]
                    contactparameter = 1.0

    [Settings.Department]
        [Settings.Department.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Department.contact_sampling_method.parameters]
                    contactparameter = 1.0

    [Settings.Workplace]
        [Settings.Workplace.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Workplace.contact_sampling_method.parameters]
                    contactparameter = 1.0
                    
    [Settings.GlobalSetting]
        [Settings.GlobalSetting.contact_sampling_method]
                type = "ContactparameterSampling"
                
                [Settings.GlobalSetting.contact_sampling_method.parameters]
                    contactparameter = 1.0